name = 'justengel_theme'
version = '1.0.0'
description = 'Jinja theme capability'
url = 'https://github.com/justengel-web/justengel_theme'
author = 'Justin Engel'
author_email = 'jtengel08@gmail.com'
